Document: avian
Title: Debian avian Manual
Author: <insert document author here>
Abstract: This manual describes what avian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/avian/avian.sgml.gz

Format: postscript
Files: /usr/share/doc/avian/avian.ps.gz

Format: text
Files: /usr/share/doc/avian/avian.text.gz

Format: HTML
Index: /usr/share/doc/avian/html/index.html
Files: /usr/share/doc/avian/html/*.html
